### ISSUE TITLE
Useless docker image for the GitLab CI/CD Pipelines.

### ISSUE THREAD

**Issue by jfsanchez-gh** [postmanlabs/newman#1948]
Useless docker image for GitLab CI/CD Pipelines.
When I try to use the postman/newman or postman/newman:ubuntu images in the GitLab CI/CD pipelines I get this error
```
error: invalid command `sh`

Usage: newman [options] [command]

Options:
  -v, --version               output the version number
  -h, --help                  output usage information

Commands:
  run [options] <collection>  URL or path to a Postman Collection.

To get available options for a command:
  newman [command] -h
error: invalid command `sh`

Usage: newman [options] [command]

Options:
  -v, --version               output the version number
  -h, --help                  output usage information

Commands:
  run [options] <collection>  URL or path to a Postman Collection.

To get available options for a command:
  newman [command] -h
```
which is becouse GitLab is executing the commands in the `script` field of the pipeline using `sh`;
then this `sh` command is passed as argument to the entrypoint of the image, which in case of the newman images, is the same newman command line. So the entrypoint receive `sh` as argument, then newman receive `sh` as argument, and then I receive that error.
Can you please provide another Docker image which does not contain the `newman` tool as default entrypoint?

This is how a GitLab CI/CD Pipeline step looks like:
```
e2e:staging:
  image: postman/newman
  stage: e2e-test
  variables:
    POSTMAN_ENVIRONMENT: service-staging.postman_environment.json
  script:
    - newman run e2e/service-collection.postman_collection.json -e e2e/$POSTMAN_ENVIRONMENT
  only:
    - develop
```

**Comment by kunagpal** [comment]
@jfsanchez-gh Could you take a look at https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#available-settings-for-image and confirm that the entrypoint override option provides what you're looking for?

**Comment by jfsanchez-gh** [comment]
@kunagpal thx for your answer and time. You are right, using this "new" (for me) feature in GitLab, you can accomplish this.
And this is how (based on my question example):
```
e2e:staging:
  image:
      name: postman/newman
      entrypoint: ["/bin/sh", "-c"]
  stage: e2e-test
  variables:
    POSTMAN_ENVIRONMENT: service-staging.postman_environment.json
  script:
    - newman run e2e/service-collection.postman_collection.json -e e2e/$POSTMAN_ENVIRONMENT
  only:
    - develop
```
**NOTE**: But, I still think it is a good idea to have a Docker image providing a different `bash` or `sh` entrypoint; maybe it is needed to run `newman` in some other platform (with Docker) that does not support it this way.
What do you think?
